apiVersion: v1
kind: Service
metadata:
  name: todo-app-client
  labels:
    app: todo-app-client
  namespace: default
  selfLink: /api/v1/namespaces/default/services/todo-app-client
spec:
  selector:
    app: todo-app-client
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    name: "8080"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
